name: V2 Convert word to markdown

on: 
  workflow_dispatch:
    # inputs:
    #   input_file:
    #     required: true
    #   output_file:
    #     required: true
    #     default: "docusaurus/docs/tutorial-basics/git.md"
      

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: output
        run: |
          mkdir output 
          find word-doc -type d | grep -v node_modules > folder.txt
          cat folder.txt
          cat folder.txt | while read LINE; do echo $LINE && mkdir -p output/$LINE && find $LINE -name \*.docx -exec cp {} output/$LINE\;  ;done 
          tree output
          rsync -arv output docusaurus/docs"
        continue-on-error: true
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docx
          path: output
      - name: test some commands
        run: |
          SHA=`git log --pretty=format:'%H' -n 1`

          echo $SHA
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          
          git checkout -b ${{ github.run_id }} 
          echo ${{ github.run_id }} > run.txt
          git add .
          git commit -m "Convert docx to markdown"

          git push -u origin ${{ github.run_id }}

          # GitHub CLI api

          

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/pulls \
            -f title="Add a markdown file to website ${{ github.event.inputs.output_file }}" \
          -f body='Please pull these awesome changes in!' \
          -f head=${{ github.run_id }} \
          -f base='main' 
          


        env:
          GH_TOKEN: ${{ github.token }}
        
          
          
